version: '3.8'

services:
  db:
    image: mysql:8.0
    # command: sudo chmod -R 755 .mysql_data
    volumes:
      # - mysql_data:/var/lib/mysql
      - .mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: main
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db

  web:
    build: .
    command: python main.py 
    volumes:
      - .:/app
    ports:
      - "8001:5000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: main

# volumes:
#   mysql_data:


